server:
  port: ${SERVER_PORT:9080}
  servlet:
    session:
      timeout: 15s

spring:
  
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${DATABASE_URL:jdbc:sqlserver://localhost:1433;databaseName=demo;trustServerCertificate=true}
    username: ${DATABASE_USERNAME:devadmin}
    password: ${DATABASE_PASSWORD:V@!aDmin2020Devusr}
    hikari:
      connection-timeout: 3000

  jmx:
    enabled: false
  main:
    banner-mode: off

  kafka:
    required: false
    bootstrap-servers: qa-kaf-1.camgsm.com.kh:9092

  redis:
    host: 172.16.101.164
    port: 32075
    password: UOWMh5uVKi
    timeout: 3000

jpa:
  hibernate:
    ddl-auto: update
  show-sql: false
  properties:
    hibernate:
      format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
  info:
    env:
      enabled: true

  endpoint:
    health:
      show-details: always
  shutdown:
    enabled: true

logging:
  level:
    org:
      springframework: #ERROR
        cloud: OFF

  pattern:
    date-format: yyyy-dd-MM HH:mm:ss.SSS
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%-20.20thread] %-38X{X-CorrelationId:-00000000-0000-0000-0000-000000000000} %-30.30logger{0} : %msg%n'

application-config:
  maintenance-mode: 'ON'
  maintenance-message: 'Sorry the service is under maintenance! Please try again later.'
  global-request-timeout-millisecond: 5
  global-connect-timeout-millisecond: 10000

