server:
  port: 8081

spring:

  application:
    name: ms-api-boilerplate
  
  datasource:
    datasource:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: ${DATABASE_URL:jdbc:sqlserver://localhost:1433;databaseName=demo;trustServerCertificate=true}
      username: ${DATABASE_USERNAME:devadmin}
      password: ${DATABASE_PASSWORD:V@!aDmin2020Devusr}
      hikari:
        connection-timeout: 3000

  kafka:
    required: true
    bootstrap-servers: prd-kaf1.cellcard.com.kh:9092,prd-kaf2.cellcard.com.kh:9092,prd-kaf3.cellcard.com.kh:9092
    group-id: sovath-test-1

  data:
    redis:
      host: localhost
      port: 6379
      password: UOWMh5uVKi
      timeout: 3000
  bus:
    enabled: false

jpa:
  hibernate:
    ddl-auto: update
  show-sql: false
  properties:
    hibernate:
      format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
  info:
    env:
      enabled: true

  endpoint:
    health:
      show-details: always
  shutdown:
    enabled: true

logging:
  level:
    org:
      springframework:
        boot: OFF
        web: OFF

  pattern:
    date-format: yyyy-dd-MM HH:mm:ss.SSS
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%-20.20thread] %-38X{X-CorrelationId:-00000000-0000-0000-0000-000000000000} %-30.30logger{0} : %msg%n'

application-config:
  maintenance-mode: 'ON'
  maintenance-message: 'Sorry the service is under maintenance! Please try again later.'
  microservices:
    ocs-service:
      base-url: "https://prd-apiserver.camgsm.com.kh/services/surepay-1111"

