server:
  port: 8081

spring:

  application:
    name: ms-api-boilerplate
  
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: 'jdbc:sqlserver://localhost:1433;databaseName=demo;trustServerCertificate=true'
    username: sa
    password: M$Dem0Dotne!
    hikari:
      connection-timeout: 3000

  kafka:
    required: false
    bootstrap-servers: localhost:9092
    group-id: sovath-test-1

  data:
    redis:
      host: localhost
      port: 6379
      password: UOWMh5uVKi
      timeout: 3000
jpa:
  hibernate:
    ddl-auto: update
  show-sql: false
  properties:
    hibernate:
      format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
  info:
    env:
      enabled: true

  endpoint:
    health:
      show-details: always
  shutdown:
    enabled: true

logging:
  level:
    org:
      springframework:
        boot: OFF
        web: OFF

  pattern:
    date-format: yyyy-dd-MM HH:mm:ss.SSS
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%-20.20thread] %-38X{X-CorrelationId:-00000000-0000-0000-0000-000000000000} %-30.30logger{0} : %msg%n'

application-config:
  microservices:
    ocs-service:
      base-url: "https://prd-apiserver.camgsm.com.kh/services/surepay"

