server:
  port: 8080

spring:

  application:
    name: ms-api-boilerplate
  
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: 'jdbc:sqlserver://localhost:1433;databaseName=demo;trustServerCertificate=true'
    username: sa
    password: M$Dem0Dotne!
    hikari:
      connection-timeout: 3000

  kafka:
    required: false

application-config:
  microservices:
    ocs-service:
      base-url: "https://prd-apiserver.camgsm.com.kh/services/surepay"

