spring:
  application:
    name: ms-api-boilerplate
  
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: 'jdbc:sqlserver://localhost:14333;databaseName=demo;trustServerCertificate=true'
    username: sa
    password: M$Dem0Dotne!
    hikari:
      connection-timeout: 3000